version: "3.9"

services:
  mysql:
    image: mysql:9.0
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#    command: >
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
